language: php
php:
  - 7.3
  - nightly
matrix:
  allow_failures:
    - php: nightly
before_install:
  - if [ "$TRAVIS_PHP_VERSION" = "7.3" ]; pecl install xdebug-2.7.0beta1; fi
before_script: composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
