language: php
php:
  - 7.3
  - nightly
matrix:
  allow_failures:
    - php: nightly
before_install:
  - [ "$TRAVIS_PHP_VERSION" = "7.3" ] && pecl install xdebug-2.7.0beta1 && echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script: composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - [ "$TRAVIS_PHP_VERSION" != "nightly" ] && wget https://scrutinizer-ci.com/ocular.phar
  - [ "$TRAVIS_PHP_VERSION" != "nightly" ] && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
